# conf port
server:
  port: 3000

# conf server or no server
spring:
  main:
    web-application-type: servlet

  # conf database address and auth
  datasource:
    url: jdbc:postgresql://localhost:5432/atos
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
