# conf port
server:
  port: 3001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/atos_document_service
    username: postgres
    password: postgres

  jpa:
    hibernate:
#      ddl-auto: update
#      ddl-auto: create
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect