server:
  port: 3001

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/document_service

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8080/.well-known/jwks.json