server:
  port: 3001

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/atos_document_service

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:3000/auth/.well-known/jwks.json
auth:
  jwks:
    url: http://localhost:3000/auth/.well-known/jwks.json

logging:
  file:
    name: /path/to/your/logs/application.log
  level:
    root: INFO
    org.springframework.web: DEBUG
    net.atos: DEBUG
    org.springframework.security: DEBUG