server:
  port: 3001

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/atos_document_service

  security:
    oauth2:
      resourceserver:
        jwt:
            jwk-set-uri: http://localhost:3000/auth/.well-known/jwks.json